
import { Player, MonthlyData, BracketMatch } from '../types';

interface AppState {
  players: Player[];
  monthlyData: MonthlyData[];
  currentMonthIndex: number;
  masterBracket: BracketMatch[];
}

export const INITIAL_STATE: AppState = {
  "players": [
    {
      "id": 1,
      "name": "Andre Mota",
      "totalPoints": 10,
      "wins": 0,
      "losses": 5,
      "gamesPlayed": 5,
      "setsWon": 0,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 2,
      "name": "Arildo",
      "totalPoints": 23,
      "wins": 1,
      "losses": 4,
      "gamesPlayed": 5,
      "setsWon": 3,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 3,
      "name": "Arthur",
      "totalPoints": 24,
      "wins": 1,
      "losses": 4,
      "gamesPlayed": 5,
      "setsWon": 4,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 4,
      "name": "Ary",
      "totalPoints": 47,
      "wins": 3,
      "losses": 2,
      "gamesPlayed": 5,
      "setsWon": 7,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 5,
      "name": "Caio Dias",
      "totalPoints": 70,
      "wins": 5,
      "losses": 0,
      "gamesPlayed": 5,
      "setsWon": 10,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 6,
      "name": "Claudio",
      "totalPoints": 59,
      "wins": 4,
      "losses": 1,
      "gamesPlayed": 5,
      "setsWon": 9,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 7,
      "name": "Cleiton",
      "totalPoints": 46,
      "wins": 3,
      "losses": 2,
      "gamesPlayed": 5,
      "setsWon": 6,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 8,
      "name": "Daniel Tomaz",
      "totalPoints": 58,
      "wins": 4,
      "losses": 1,
      "gamesPlayed": 5,
      "setsWon": 8,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 9,
      "name": "Diego Rodrigues",
      "totalPoints": 46,
      "wins": 3,
      "losses": 2,
      "gamesPlayed": 5,
      "setsWon": 6,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 10,
      "name": "Evaldo",
      "totalPoints": 59,
      "wins": 4,
      "losses": 1,
      "gamesPlayed": 5,
      "setsWon": 9,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 11,
      "name": "Fernando Garpelli",
      "totalPoints": 22,
      "wins": 1,
      "losses": 4,
      "gamesPlayed": 5,
      "setsWon": 2,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 12,
      "name": "Fernando Martin",
      "totalPoints": 35,
      "wins": 2,
      "losses": 3,
      "gamesPlayed": 5,
      "setsWon": 5,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 13,
      "name": "Fernando Soares",
      "totalPoints": 35,
      "wins": 2,
      "losses": 3,
      "gamesPlayed": 5,
      "setsWon": 5,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 14,
      "name": "Flavio",
      "totalPoints": 24,
      "wins": 1,
      "losses": 4,
      "gamesPlayed": 5,
      "setsWon": 4,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 15,
      "name": "Gabriel Abrame",
      "totalPoints": 47,
      "wins": 3,
      "losses": 2,
      "gamesPlayed": 5,
      "setsWon": 7,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 16,
      "name": "Gilson Santana",
      "totalPoints": 32,
      "wins": 2,
      "losses": 3,
      "gamesPlayed": 5,
      "setsWon": 4,
      "pointsFromGames": 8,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 17,
      "name": "Guilherme Tadini",
      "totalPoints": 70,
      "wins": 5,
      "losses": 0,
      "gamesPlayed": 5,
      "setsWon": 10,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 18,
      "name": "Gustavo Granja",
      "totalPoints": 58,
      "wins": 4,
      "losses": 1,
      "gamesPlayed": 5,
      "setsWon": 8,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 19,
      "name": "Iramaia",
      "totalPoints": 36,
      "wins": 2,
      "losses": 3,
      "gamesPlayed": 5,
      "setsWon": 6,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 20,
      "name": "Joao Claudio",
      "totalPoints": 23,
      "wins": 1,
      "losses": 4,
      "gamesPlayed": 5,
      "setsWon": 3,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 21,
      "name": "Joao Vicente",
      "totalPoints": 12,
      "wins": 0,
      "losses": 5,
      "gamesPlayed": 5,
      "setsWon": 2,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 22,
      "name": "João Orsi",
      "totalPoints": 47,
      "wins": 3,
      "losses": 2,
      "gamesPlayed": 5,
      "setsWon": 7,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 23,
      "name": "José Eduardo",
      "totalPoints": 47,
      "wins": 3,
      "losses": 2,
      "gamesPlayed": 5,
      "setsWon": 7,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 24,
      "name": "Leo Alves",
      "totalPoints": 46,
      "wins": 3,
      "losses": 2,
      "gamesPlayed": 5,
      "setsWon": 6,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 25,
      "name": "Lincoln",
      "totalPoints": 58,
      "wins": 4,
      "losses": 1,
      "gamesPlayed": 5,
      "setsWon": 8,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 26,
      "name": "Luan",
      "totalPoints": 34,
      "wins": 2,
      "losses": 3,
      "gamesPlayed": 5,
      "setsWon": 4,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 27,
      "name": "Lucas Lima",
      "totalPoints": 32,
      "wins": 2,
      "losses": 3,
      "gamesPlayed": 5,
      "setsWon": 4,
      "pointsFromGames": 8,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 28,
      "name": "Luiz Fernando",
      "totalPoints": 35,
      "wins": 2,
      "losses": 3,
      "gamesPlayed": 5,
      "setsWon": 5,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 29,
      "name": "Marcelo Bassi",
      "totalPoints": 28,
      "wins": 2,
      "losses": 3,
      "gamesPlayed": 5,
      "setsWon": 4,
      "pointsFromGames": 4,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 30,
      "name": "Marcelo Candido",
      "totalPoints": 35,
      "wins": 2,
      "losses": 3,
      "gamesPlayed": 5,
      "setsWon": 5,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 31,
      "name": "Marcos Rodrigues",
      "totalPoints": 34,
      "wins": 2,
      "losses": 3,
      "gamesPlayed": 5,
      "setsWon": 4,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 32,
      "name": "Mario",
      "totalPoints": 46,
      "wins": 3,
      "losses": 2,
      "gamesPlayed": 5,
      "setsWon": 6,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 33,
      "name": "Paulo Soares",
      "totalPoints": 45,
      "wins": 3,
      "losses": 2,
      "gamesPlayed": 5,
      "setsWon": 7,
      "pointsFromGames": 8,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 34,
      "name": "Pedro",
      "totalPoints": 58,
      "wins": 4,
      "losses": 1,
      "gamesPlayed": 5,
      "setsWon": 8,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 35,
      "name": "Rafael Brandao",
      "totalPoints": 23,
      "wins": 1,
      "losses": 4,
      "gamesPlayed": 5,
      "setsWon": 3,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 36,
      "name": "Renan Martin",
      "totalPoints": 35,
      "wins": 2,
      "losses": 3,
      "gamesPlayed": 5,
      "setsWon": 5,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 37,
      "name": "Robson Fiusa",
      "totalPoints": 70,
      "wins": 5,
      "losses": 0,
      "gamesPlayed": 5,
      "setsWon": 10,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 38,
      "name": "Tadeu Maia",
      "totalPoints": 4,
      "wins": 0,
      "losses": 5,
      "gamesPlayed": 5,
      "setsWon": 0,
      "pointsFromGames": 4,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 39,
      "name": "Thiago Mello",
      "totalPoints": 59,
      "wins": 4,
      "losses": 1,
      "gamesPlayed": 5,
      "setsWon": 9,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    },
    {
      "id": 40,
      "name": "Tiago Meira",
      "totalPoints": 35,
      "wins": 2,
      "losses": 3,
      "gamesPlayed": 5,
      "setsWon": 5,
      "pointsFromGames": 10,
      "totalWoWins": 0,
      "totalWoLosses": 0,
      "monthlyPoints": 0,
      "monthlyWins": 0,
      "monthlyLosses": 0,
      "monthlyGamesPlayed": 0,
      "monthlySetsWon": 0,
      "monthlyPointsFromGames": 0,
      "monthlyWoWins": 0,
      "monthlyWoLosses": 0
    }
  ],
  "monthlyData": [
    {
      "id": 1,
      "name": "Outubro",
      "groups": [
        { "id": 1, "name": "Grupo 1", "playerIds": [5, 17, 37, 6] },
        { "id": 2, "name": "Grupo 2", "playerIds": [39, 10, 8, 18] },
        { "id": 3, "name": "Grupo 3", "playerIds": [25, 34, 4, 15] },
        { "id": 4, "name": "Grupo 4", "playerIds": [22, 23, 7, 9] },
        { "id": 5, "name": "Grupo 5", "playerIds": [24, 32, 33, 19] },
        { "id": 6, "name": "Grupo 6", "playerIds": [12, 13, 28, 30] },
        { "id": 7, "name": "Grupo 7", "playerIds": [36, 40, 26, 31] },
        { "id": 8, "name": "Grupo 8", "playerIds": [16, 27, 29, 3] },
        { "id": 9, "name": "Grupo 9", "playerIds": [14, 2, 20, 35] },
        { "id": 10, "name": "Grupo 10", "playerIds": [11, 21, 1, 38] }
      ],
      "matches": [
        { "id": "m1-g1-p5-vs-p17", "player1Id": 5, "player2Id": 17, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g1-p5-vs-p37", "player1Id": 5, "player2Id": 37, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g1-p5-vs-p6", "player1Id": 5, "player2Id": 6, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g1-p17-vs-p37", "player1Id": 17, "player2Id": 37, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g1-p17-vs-p6", "player1Id": 17, "player2Id": 6, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g1-p37-vs-p6", "player1Id": 37, "player2Id": 6, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g2-p39-vs-p10", "player1Id": 39, "player2Id": 10, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g2-p39-vs-p8", "player1Id": 39, "player2Id": 8, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g2-p39-vs-p18", "player1Id": 39, "player2Id": 18, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g2-p10-vs-p8", "player1Id": 10, "player2Id": 8, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g2-p10-vs-p18", "player1Id": 10, "player2Id": 18, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g2-p8-vs-p18", "player1Id": 8, "player2Id": 18, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g3-p25-vs-p34", "player1Id": 25, "player2Id": 34, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g3-p25-vs-p4", "player1Id": 25, "player2Id": 4, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g3-p25-vs-p15", "player1Id": 25, "player2Id": 15, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g3-p34-vs-p4", "player1Id": 34, "player2Id": 4, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g3-p34-vs-p15", "player1Id": 34, "player2Id": 15, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g3-p4-vs-p15", "player1Id": 4, "player2Id": 15, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g4-p22-vs-p23", "player1Id": 22, "player2Id": 23, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g4-p22-vs-p7", "player1Id": 22, "player2Id": 7, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g4-p22-vs-p9", "player1Id": 22, "player2Id": 9, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g4-p23-vs-p7", "player1Id": 23, "player2Id": 7, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g4-p23-vs-p9", "player1Id": 23, "player2Id": 9, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g4-p7-vs-p9", "player1Id": 7, "player2Id": 9, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g5-p24-vs-p32", "player1Id": 24, "player2Id": 32, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g5-p24-vs-p33", "player1Id": 24, "player2Id": 33, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g5-p24-vs-p19", "player1Id": 24, "player2Id": 19, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g5-p32-vs-p33", "player1Id": 32, "player2Id": 33, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g5-p32-vs-p19", "player1Id": 32, "player2Id": 19, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g5-p33-vs-p19", "player1Id": 33, "player2Id": 19, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g6-p12-vs-p13", "player1Id": 12, "player2Id": 13, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g6-p12-vs-p28", "player1Id": 12, "player2Id": 28, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g6-p12-vs-p30", "player1Id": 12, "player2Id": 30, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g6-p13-vs-p28", "player1Id": 13, "player2Id": 28, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g6-p13-vs-p30", "player1Id": 13, "player2Id": 30, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g6-p28-vs-p30", "player1Id": 28, "player2Id": 30, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g7-p36-vs-p40", "player1Id": 36, "player2Id": 40, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g7-p36-vs-p26", "player1Id": 36, "player2Id": 26, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g7-p36-vs-p31", "player1Id": 36, "player2Id": 31, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g7-p40-vs-p26", "player1Id": 40, "player2Id": 26, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g7-p40-vs-p31", "player1Id": 40, "player2Id": 31, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g7-p26-vs-p31", "player1Id": 26, "player2Id": 31, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g8-p16-vs-p27", "player1Id": 16, "player2Id": 27, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g8-p16-vs-p29", "player1Id": 16, "player2Id": 29, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g8-p16-vs-p3", "player1Id": 16, "player2Id": 3, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g8-p27-vs-p29", "player1Id": 27, "player2Id": 29, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g8-p27-vs-p3", "player1Id": 27, "player2Id": 3, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g8-p29-vs-p3", "player1Id": 29, "player2Id": 3, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g9-p14-vs-p2", "player1Id": 14, "player2Id": 2, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g9-p14-vs-p20", "player1Id": 14, "player2Id": 20, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g9-p14-vs-p35", "player1Id": 14, "player2Id": 35, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g9-p2-vs-p20", "player1Id": 2, "player2Id": 20, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g9-p2-vs-p35", "player1Id": 2, "player2Id": 35, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g9-p20-vs-p35", "player1Id": 20, "player2Id": 35, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g10-p11-vs-p21", "player1Id": 11, "player2Id": 21, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g10-p11-vs-p1", "player1Id": 11, "player2Id": 1, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g10-p11-vs-p38", "player1Id": 11, "player2Id": 38, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g10-p21-vs-p1", "player1Id": 21, "player2Id": 1, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g10-p21-vs-p38", "player1Id": 21, "player2Id": 38, "winnerId": null, "score": "", "isWO": false },
        { "id": "m1-g10-p1-vs-p38", "player1Id": 1, "player2Id": 38, "winnerId": null, "score": "", "isWO": false }
      ]
    }
  ],
  "currentMonthIndex": 0,
  "masterBracket": []
};